### PR TITLE
Update links to api key docs

### PR DESCRIPTION
**Pull request by wontruefree**
## Motivation

When looking for links on tokens I noticed the links on `npmjs.com` and `github.com` are broken.

## Changes

Update the links to the `docs.datadoghq.com` pages.

## Testing

- [ ] Local
- [ ] Staging
- [ ] Unit
- [ ] End to end

---

I have gone over the [contributing](https://github.com/DataDog/browser-sdk/blob/main/CONTRIBUTING.md) documentation.

### CODE REVIEW

**Comment by BenoitZugmeyer** [comment]
@wontruefree could you [sign our CLA](https://cla.datadoghq.com/DataDog/browser-sdk?pullRequest=1508) so I can merge your PR?

**Review by maycmlee — APPROVED** [review]
👍  for docs.

**Comment by wontruefree** [comment]
@BenoitZugmeyer thanks for the bump.  I signed the CLA.

**Comment by BenoitZugmeyer** [comment]
@wontruefree Thank you for your contribution!

**Pull request merged**
