### PR TITLE
support exactOptionalPropertyTypes for rum init

### PR DESCRIPTION
**Pull request by CharlesStover**
## Motivation

Users with `exactOptionalPropertyTypes` enabled in TypeScript cannot pass `undefined` to RUM `init` properties, making some code verbose.

[Example](https://github.com/CharlesStover/charlesstover.com/blob/main/src/modules/react-datadog/components/datadog/datadog.root.view.tsx#L68)

## Changes

Explicitly allows `undefined` for optional properties.

## Testing

I have gone over the [contributing](https://github.com/DataDog/browser-sdk/blob/main/CONTRIBUTING.md) documentation.

## Notes

This is a change that should likely be app-wide, but I really just want to shorten the code I'm writing today and would appreciate large efforts to be separate PRs to unblock me. 🙃

Thank you,

### CODE REVIEW

**Comment by BenoitZugmeyer** [comment]
Thanks for your PR. It looks good, we just want to ensure that we don't break compatibility with this TS option in the future, so we want to add it to the [test app](https://github.com/DataDog/browser-sdk/blob/main/test/app/tsconfig.json). We'll look into it shortly.

**Comment by CharlesStover** [comment]
@BenoitZugmeyer Is there an update on this? This PR at least would unblock me if y'all need more time internally for a larger scoped change.

**Comment by BenoitZugmeyer** [comment]
It is still in our pipe, I think we should be able to sort it out this week

**Comment by BenoitZugmeyer** [comment]
@CharlesStover because our CI does not currently run on external PRs, I opened #1082 for your changes. I also added a small compatibility check. This PR will be reviewed by the rest of the team and then released in the coming days. Don't hesitate to comment there. Thank you for your contribution!

**Comment by bcaudan** [comment]
Hi @CharlesStover,

The change is available with [v3.6.6](https://github.com/DataDog/browser-sdk/blob/main/CHANGELOG.md#v366).

**Pull request closed without merging**
