### PR TITLE
feat(trackXhr): make xhr tracking work with Angular

### PR DESCRIPTION
**Pull request by keitoaino**
For some reason Angular aborts XHR requests after Angular finishes its internal processing of requests. As a result with XHR tracking using `loadend` event we get `status: 0` and each XHR is being tracked as a failed request with DataDog library.
Using `onreadystatechange` for tracking resolves issue with Angular and doesn't affect regular calls with `XMLHttpRequest`

### CODE REVIEW

**Comment by bcaudan** [comment]
Hi @keitoaino!
Thanks for your PR, we will look into it and keep you posted.

**Comment by keitoaino** [comment]
Hi @bcaudan!
Any progress on reviewing my PR? :) Thanks!

**Comment by bcaudan** [comment]
Hi @keitoaino, we have just released the 1.6.3 which should fix your issue.

**Comment by keitoaino** [comment]
@bcaudan thanks!

**Pull request closed without merging**
