### PR TITLE
✨ track all programmatically-named-actions

### PR DESCRIPTION
**Pull request by treyesmond**
## Motivation

I am a developer on an Indeed platform team, and we have encountered unexpected behavior with the Datadog RUM [programmatically named user actions](https://docs.datadoghq.com/real_user_monitoring/browser/tracking_user_actions/?tab=npm#declaring-a-name-for-click-actions) feature.

#### Expectation

> User clicks on DOM elements that include the `data-dd-action-name` attribute are tracked.

#### Observed Behavior

> Some programmatically named user interactions are not tracked due to lack of a correlated DOM activity or network request.

The [automatic click tracking event filter rules](https://docs.datadoghq.com/real_user_monitoring/browser/tracking_user_actions/?tab=npm#what-interactions-are-being-tracked) are a perfectly sensible approach to determining which uninstrumented events are important enough to capture. Unfortunately, the activity detection requirement is also being applied to events which are being explicitly, programmatically instrumented using the `data-dd-action-name` attribute. The use of this attribute indicates that the event is important and signals developer intent to track all user click actions for the tagged element.

## Changes

The `getActionNameFromElement` user action tracking helper returns a tuple that includes metadata about whether the action name was found to be programmatically named or inferred by a fallback strategy. This information allows the action tracking management engine to `complete` rather than `discard` any programmatically named actions that lack a correlated DOM activity or network request.

This change will not affect the default automatic user interaction tracking behavior. Interactions which have been explicitly instrumented using the `data-dd-action-name` attribute will generate a higher number of RUM events. This is not expected to be a proportionally large increase compared to current behavior since most programmatically named actions already correlate with DOM / network activity. The new behavior is simply filling in gaps of missed data.

## Testing

Comprehensive unit and e2e tests have been added for all touched codepaths. Additionally, I was able to directly verify the changes in an internal branch build of the Indeed system that uses `@datadog/browser-rum` by locally building the package and directly installing from the tarball.

#### Generalized test steps

- In a sandbox environment, build a set of buttons with the following variations:
  1. `<button onclick="someDomMutation()">Auto With Action<button>`
  2. `<button>Auto No Action</button>`
  3. `<button data-dd-action-name="named with action" onclick="someDomMutation()">Named With Action</button>`
  4. `<button data-dd-action-name="named no action">Named No Action</button>`
- Load the environment in a browser.
- Click on each button.
- Open the [datadog rum explorer](https://app.datadoghq.com/rum/explorer) and look at actions filtered by the sandbox environment's app id.
- An action for variation 1 ("click on Auto With Action") should be logged.
- An action for variation 2 should not be logged.
- An action for variation 3 ("click on named with action") should be logged.
- An action for variation 4 ("click on named no action") should be logged. Note that it will not include an `Action Loading Time` property since no associated action was found.

---

I have gone over the [contributing](https://github.com/DataDog/browser-sdk/blob/main/CONTRIBUTING.md) documentation.

### CODE REVIEW

**Comment by bcaudan** [comment]
Hi @treyesmond,

Thanks for the contribution, that it is a very interesting approach!
We'll discuss it internally and get back to you.

**Comment by treyesmond** [comment]
Checking in to see if there's been any further discussion about this one. Thanks!

**Comment by hdelaby** [comment]
Hi @treyesmond I'm from the product management team. We discussed it internally and we are super enthusiastic about this change. Now we need to review the UI implications of it, which is something I plan on doing over the next few days.

So far, automatically collected actions (clicks only) have always had a duration attached. We should make sure nothing relies on that condition, or update it, before we can go live with your suggestion. I hope this makes sense.

**Comment by treyesmond** [comment]
Thanks for the status update @hdelaby!

**Comment by bcaudan** [comment]
I am closing this PR for now but keep track of the feature in https://github.com/DataDog/browser-sdk/issues/949

**Pull request closed without merging**
