### PR TITLE
⚡️ [RUM-7650] Delay the viewport dimension collection

### PR DESCRIPTION
**Pull request by amortemousque**
## Motivation

Accessing viewport dimensions triggers forced reflows, potentially adding up to 50ms to the SDK initialization, resulting in a long task and degrading Total Blocking Time (TBT). This PR collects viewport dimensions asynchronously to decouple the reflow from initialization, minimizing its impact on TBT.

<table>
<tr><th>Before</th><th>After</th></tr>
<tr><td>Screenshot 2024-12-11 at 15 24 24</td><td>Screenshot 2024-12-11 at 15 26 43</td></tr>
</table>

## Changes

Use `requestAnimationFrame` to collect viewport dimensions

## Testing

- [x] Local
- [ ] Staging
- [x] Unit
- [ ] End to end

---

I have gone over the [contributing](https://github.com/DataDog/browser-sdk/blob/main/CONTRIBUTING.md) documentation.

### CODE REVIEW

**Review by cy-moi — APPROVED** [review]
🚀 🚀 🌕

**Review by thomas-lebeau — APPROVED** [review]

**Pull request merged**
