### PR TITLE
🐛[RUMF-645] do not track intake request errors

### PR DESCRIPTION
**Pull request by bcaudan**
## Motivation

Intake request errors are reported which cause a loop of errors 

## Changes

Exclude intake request errors like intake resource events

## Testing

Automated tests

---

I have gone over the [contributing](https://github.com/DataDog/browser-sdk/blob/master/CONTRIBUTING.md) documentation.

### CODE REVIEW

**Review by glorieux — APPROVED** [review]

**Review by BenoitZugmeyer — COMMENTED** [review]
Why not filtering requests at the proxy level directly?

* idealy, intake requests should not impact the `trackPageActivity`
* if we were to use those proxies for something else (ex: trace integration), we wouldn't need to think about checking if the request is an intake request.

**Comment by bcaudan** [comment]
> Why not filtering requests at the proxy level directly?
> 
> * idealy, intake requests should not impact the `trackPageActivity`
> * if we were to use those proxies for something else (ex: trace integration), we wouldn't need to think about checking if the request is an intake request.

In this case, it would work but I would prefer to avoid putting any domain logic in these proxies.
On npm, they are reused between logs/rum instance so it is not a good idea to add a dependency on the configuration that could be different between products.

> idealy, intake requests should not impact the `trackPageActivity`

if we want to tackle that now, we could move the `shouldTrackResource` to `requestCollection` and `performanceCollection` (we can have intake request here too)

> * if we were to use those proxies for something else (ex: trace integration), we wouldn't need to think about checking if the request is an intake request.

for previous PR on trace integration, we used `requestCollection` so above strategy should work

wdyt?

**Comment by BenoitZugmeyer** [comment]
> > Why not filtering requests at the proxy level directly?
> > 
> > * idealy, intake requests should not impact the `trackPageActivity`
> > * if we were to use those proxies for something else (ex: trace integration), we wouldn't need to think about checking if the request is an intake request.
> 
> In this case, it would work but I would prefer to avoid putting any domain logic in these proxies.
> On npm, they are reused between logs/rum instance so it is not a good idea to add a dependency on the configuration that could be different between products.

That's a very good point, which raises another issue: if the request to the RUM intake fails, the failed request will still be logged, since the logs SDK has no knowledge of the RUM intake configuration, isn't it?

> 
> > idealy, intake requests should not impact the `trackPageActivity`
> 
> if we want to tackle that now, we could move the `shouldTrackResource` to `requestCollection` and `performanceCollection` (we can have intake request here too)
> 
> > * if we were to use those proxies for something else (ex: trace integration), we wouldn't need to think about checking if the request is an intake request.
> 
> for previous PR on trace integration, we used `requestCollection` so above strategy should work
> 
> wdyt?

It seems to be a good strategy, to be done in a separate PR maybe?

**Comment by bcaudan** [comment]
> That's a very good point, which raises another issue: if the request to the RUM intake fails, the failed request will still be logged, since the logs SDK has no knowledge of the RUM intake configuration, isn't it?

all intake endpoints are computed in `core/configuration` regardless of the SDK (logs or RUM)

> It seems to be a good strategy, to be done in a separate PR maybe?

sounds good to me

**Comment by BenoitZugmeyer** [comment]
> > That's a very good point, which raises another issue: if the request to the RUM intake fails, the failed request will still be logged, since the logs SDK has no knowledge of the RUM intake configuration, isn't it?
> 
> all intake endpoints are computed in `core/configuration` regardless of the SDK (logs or RUM)

Ok so it will work as long as LOGS and RUM are using the same transport configuration (site, proxyHost, internalMonitoringKey, buildMode). Seems fair to me.

**Review by BenoitZugmeyer — APPROVED** [review]

**Pull request merged**
