### PR TITLE
Support logging from web workers

### PR DESCRIPTION
**Pull request by cguirguis**
Because many of the methods in browser-sdk reference objects that are not available in web workers -- like `window` and `document` -- it renders the library dysfunctional in web applications that utilize workers. 

This PR updates all relevant `window`/`document` references to use `self`, which is more flexible.

### CODE REVIEW

**Comment by bcaudan** [comment]
Hi @cguirguis,

Thanks for you PR, for now our repository is not really contribution friendly since we don't have a public CI 😕
We'll have a look at your PR and get back to you.

**Comment by cguirguis** [comment]
Hi Bastien,

Any update on this? Would really appreciate having your team incorporate
these changes into the library. The set of changes is super limited and
safe.

Let me know if I can help.

Thanks,
Chris

**Comment by bcaudan** [comment]
Hi @cguirguis,

What we have in mind before integrating this PR:

- ensure that using self behaves correctly in older browsers (IE)
- set up a web worker test to prevent any regression on that topic

Unfortunately, since this behavior is not requested by many customers it is not in our top priorities right now.
It is definitely something that we would want to integrate but it could take some time before we make progress on that.

Let me know if you have any questions.

**Comment by bcaudan** [comment]
I am closing this PR but I have opened a corresponding issue to follow this topic: #432

**Comment by MrLemur** [comment]
@cguirguis Do these changes require a different initialisation of the library from the browser?

**Pull request closed without merging**
