### PR TITLE
[RUM] 🐛 call previously installed onunhandledrejection handler

### PR DESCRIPTION
**Pull request by michaelmcchen**
## Motivation

https://github.com/DataDog/browser-sdk/issues/541 confirmed that the existing behavior of ignoring the previously installed `onunhandledrejection` handler is a bug; this PR fixes it

## Testing

I tested this out against my project (that first raised the issue) as well as added an unit test to `tracekit.spec.ts`.

---

I have gone over the [contributing](https://github.com/DataDog/browser-sdk/blob/master/CONTRIBUTING.md) documentation.

### CODE REVIEW

**Comment by michaelmcchen** [comment]
Agreement review in progress, just wanted to put up this PR in the meantime for feedback.

**Comment by bcaudan** [comment]
Hi @michaelmcchen, thanks for this PR!

Code looks good to me but could you have a look at issues raised by `yarn lint` and `yarn format`?

**Review by bcaudan — APPROVED** [review]

**Comment by bcaudan** [comment]
Hi @michaelmcchen, did you have a chance to review the CLA?

**Comment by michaelmcchen** [comment]
Hey @bcaudan, my org requires that our legal team reviews any contracts that we sign, including open-source CLA's. That's currently in progress at the moment - sorry for the delay!

**Comment by bcaudan** [comment]
Feel free to re-open a new one if you manage to get the approval for CLA and if the related issue is still not fixed

**Pull request closed without merging**
