### PR TITLE
🔥 [RUMF-1093] deprecated proxyhost option

### PR DESCRIPTION
**Pull request by amortemousque**
## Motivation

Remove the proxyHost option and related implementation

## Changes

Update endpoint builder

## Testing

- [x] Local
- [ ] Staging
- [x] Unit
- [ ] End to end

---

I have gone over the [contributing](https://github.com/DataDog/browser-sdk/blob/main/CONTRIBUTING.md) documentation.

### CODE REVIEW

**Review by BenoitZugmeyer — COMMENTED** [review]
Because the logic to build endpoint URLs is getting simpler, I was wondering if we couldn't reduce the complexity by:

* removing internal functions
* returning URLs directly instead of 'build' functions

See https://gist.github.com/BenoitZugmeyer/3c4120d9c0a64afeafdf54cb0e2b44ef 
WDYT?

**Comment by amortemousque** [comment]
> Because the logic to build endpoint URLs is getting simpler, I was wondering if we couldn't reduce the complexity by:
> 
> * removing internal functions
> * returning URLs directly instead of 'build' functions
> 
> See https://gist.github.com/BenoitZugmeyer/3c4120d9c0a64afeafdf54cb0e2b44ef WDYT?

The only issue I see, I that dd-request-id and batch_time have to be build for each request. How would you manage it?

**Comment by BenoitZugmeyer** [comment]
Ah right. Well we could still simplify it, but keep the `build()` function?

**Comment by amortemousque** [comment]
> 

Yes nice :) I'm doing it

**Review by BenoitZugmeyer — APPROVED** [review]
Nice!

**Review by bcaudan — APPROVED** [review]

**Pull request merged**
