### PR TITLE
✨ [RUM-4287] Enable feature flags API

### PR DESCRIPTION
**Pull request by amortemousque**
## Motivation

This PR enables sending feature flags with the API introduced in https://github.com/DataDog/browser-sdk/pull/2096

## Changes

Remove the `feature_flags` experimental flag.

## Testing

- [ ] Local
- [X] Staging
- [X] Unit
- [X] End to end

---

I have gone over the [contributing](https://github.com/DataDog/browser-sdk/blob/main/CONTRIBUTING.md) documentation.

### CODE REVIEW

**Review by N-Boutaib — APPROVED** [review]
LGTM

**Review by acorretti — APPROVED** [review]

**Review by bcaudan — APPROVED** [review]
🎉

**Comment by bbrzoska** [comment]
Looks like the docs need to be updated, as [they still say](https://docs.datadoghq.com/real_user_monitoring/guide/setup-feature-flag-data-collection/?tab=browser#setup) the flag should be added to config.

**Comment by BenoitZugmeyer** [comment]
Good catch! It's being worked on :) https://github.com/DataDog/documentation/pull/25073#discussion_r1751470970

**Pull request merged**
