### PR TITLE
🐛 fix Could not load source file warning when bundling with Parcel

### PR DESCRIPTION
**Pull request by HHogg**
## Motivation

The package is building fine with Parcel, but it is leaving a lot of noisy logs due to the `src` folder being excluded from the published package.  

You can replicate this like... 

```
mkdir source-map-example
cd source-map-example
yarn init -y
yarn add parcel @datadog/browser-rum
echo "import { datadogRum } from '@datadog/browser-rum';" > index.js
yarn parcel start index.js
```

Which you'll see the follow warnings.

```
⚠️ Could not load source file "../src/index.ts" in source map of "../node_modules/@datadog/browser-logs/esm/index.js".
⚠️ Could not load source file "../src/index.ts" in source map of "../node_modules/@datadog/browser-rum/esm/index.js".
⚠️ Could not load source file "../src/logs.entry.ts" in source map of "../node_modules/@datadog/browser-logs/esm/logs.entry.js".
⚠️ Could not load source file "../src/logger.ts" in source map of "../node_modules/@datadog/browser-logs/esm/logger.js".
⚠️ Could not load source file "../src/rum.entry.ts" in source map of "../node_modules/@datadog/browser-rum/esm/rum.entry.js".
⚠️ Could not load source file "../src/rum.ts" in source map of "../node_modules/@datadog/browser-rum/esm/rum.js".
⚠️ Could not load source file "../src/rumSession.ts" in source map of "../node_modules/@datadog/browser-rum/esm/rumSession.js".
⚠️ Could not load source file "../src/userActionCollection.ts" in source map of "../node_modules/@datadog/browser-rum/esm/userActionCollection.js".
⚠️ Could not load source file "../src/performanceCollection.ts" in source map of "../node_modules/@datadog/browser-rum/esm/performanceCollection.js".
⚠️ Could not load source file "../src/viewCollection.ts" in source map of "../node_modules/@datadog/browser-rum/esm/viewCollection.js".
⚠️ Could not load source file "../src/domMutationCollection.ts" in source map of "../node_modules/@datadog/browser-rum/esm/domMutationCollection.js".
⚠️ Could not load source file "../src/index.ts" in source map of "../node_modules/@datadog/browser-core/esm/index.js".
⚠️ Could not load source file "../src/buildEnv.ts" in source map of "../node_modules/@datadog/browser-logs/esm/buildEnv.js".
⚠️ Could not load source file "../src/lifeCycle.ts" in source map of "../node_modules/@datadog/browser-rum/esm/lifeCycle.js".
⚠️ Could not load source file "../src/buildEnv.ts" in source map of "../node_modules/@datadog/browser-rum/esm/buildEnv.js".
⚠️ Could not load source file "../src/matchRequestTiming.ts" in source map of "../node_modules/@datadog/browser-rum/esm/matchRequestTiming.js".
⚠️ Could not load source file "../src/resourceUtils.ts" in source map of "../node_modules/@datadog/browser-rum/esm/resourceUtils.js".
⚠️ Could not load source file "../src/trackEventCounts.ts" in source map of "../node_modules/@datadog/browser-rum/esm/trackEventCounts.js".
⚠️ Could not load source file "../src/trackPageActivities.ts" in source map of "../node_modules/@datadog/browser-rum/esm/trackPageActivities.js".
⚠️ Could not load source file "../src/getActionNameFromElement.ts" in source map of "../node_modules/@datadog/browser-rum/esm/getActionNameFromElement.js".
⚠️ Could not load source file "../src/loggerSession.ts" in source map of "../node_modules/@datadog/browser-logs/esm/loggerSession.js".
⚠️ Could not load source file "../src/observable.ts" in source map of "../node_modules/@datadog/browser-core/esm/observable.js".
⚠️ Could not load source file "../src/sessionManagement.ts" in source map of "../node_modules/@datadog/browser-core/esm/sessionManagement.js".
⚠️ Could not load source file "../src/init.ts" in source map of "../node_modules/@datadog/browser-core/esm/init.js".
⚠️ Could not load source file "../src/internalMonitoring.ts" in source map of "../node_modules/@datadog/browser-core/esm/internalMonitoring.js".
⚠️ Could not load source file "../src/urlPolyfill.ts" in source map of "../node_modules/@datadog/browser-core/esm/urlPolyfill.js".
⚠️ Could not load source file "../src/utils.ts" in source map of "../node_modules/@datadog/browser-core/esm/utils.js".
⚠️ Could not load source file "../src/cookie.ts" in source map of "../node_modules/@datadog/browser-core/esm/cookie.js".
⚠️ Could not load source file "../src/errorCollection.ts" in source map of "../node_modules/@datadog/browser-core/esm/errorCollection.js".
⚠️ Could not load source file "../src/configuration.ts" in source map of "../node_modules/@datadog/browser-core/esm/configuration.js".
⚠️ Could not load source file "../src/requestCollection.ts" in source map of "../node_modules/@datadog/browser-core/esm/requestCollection.js".
⚠️ Could not load source file "../src/transport.ts" in source map of "../node_modules/@datadog/browser-core/esm/transport.js".
⚠️ Could not load source file "../src/specHelper.ts" in source map of "../node_modules/@datadog/browser-core/esm/specHelper.js".
⚠️ Could not load source file "../src/tracekit.ts" in source map of "../node_modules/@datadog/browser-core/esm/tracekit.js".
⚠️ Could not load source file "../src/oldCookiesMigration.ts" in source map of "../node_modules/@datadog/browser-core/esm/oldCookiesMigration.js".
```

## Changes

Changes the NPM ignore files to include the src folder. 

## Testing

Rerun the commands given above, but with the src folders and there will be no warnings. 

---

I have gone over the [contributing](https://github.com/DataDog/browser-sdk/blob/master/CONTRIBUTING.md) documentation.

### CODE REVIEW

**Review by BenoitZugmeyer — APPROVED** [review]

**Comment by BenoitZugmeyer** [comment]
@HHogg thank you for your PR! It will be released as part as the next version.

**Comment by HHogg** [comment]
No problem @BenoitZugmeyer and thanks for merging so quickly. Do you have a rough idea when this will be released? (It's a ticket in our sprint, which is now in the blocked column 🙃)

**Comment by BenoitZugmeyer** [comment]
Ha, nothing is preventing us to make a small patch release for this. I'll work on this tomorrow!

**Comment by BenoitZugmeyer** [comment]
This has been released in 1.20.1. Thanks again!

**Comment by HHogg** [comment]
Thanks for sorting this out so quickly @BenoitZugmeyer.

**Pull request merged**
